# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_check_args: --as-cran

before_script:
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; 
    then 
    ( Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& ; 
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; 
    then 
    sh -e /etc/init.d/xvfb start ;
    fi 
  - sleep 3
  
os: 
  - linux
  - osx

bioc_required: yes
use_bioc: yes
r:
- release
- devel
addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev