# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages

services:
  - xvfb

before_script:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - codename=`linux_codename`;
  - if [ "${codename}" = "trusty" ];
    then
      start_xvfb ;
    fi  
  
os: 
  - linux
  - osx

bioc_required: yes
use_bioc: yes
r:
- release
- devel
