# Neuroconductor Template
# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  - rm -f travis-tool.sh
  - ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

platform: x64

environment:
  global:
    NOT_CRAN: true    
    USE_RTOOLS: true
    # R_CHECK_INSTALL_ARGS: "--install-args=--build --no-multiarch "
    R_CHECK_ARGS: "--no-multiarch --no-manual "
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true    
    WARNINGS_ARE_ERRORS: 1


install:
  - ps: Bootstrap


cache:
  - C:\RLibrary

# Adapt as necessary starting from here
build_script:
  - travis-tool.sh install_deps

test_script:
  - choco install ffmpeg & exit 0
  - choco install dcmtk & exit 0
  - choco install libreoffice-fresh & exit 0
  - if not exist "C:\rtm" mkdir C:\rtm
  - set TMP=C:/rtm
  - set TEMP=C:/rtm
  - set TMPDIR=C:/rtm
  # need to move to higher dir because CMake path req
  - if not exist "C:\run" mkdir C:\run
  - cp -avrTf . C:\run
  # need the tool a level above
  - cp ../travis-tool.sh C:\
  - cd C:\run
  - travis-tool.sh run_tests
  - ls
  - ls ../
  # - cp ../*.zip ./
  - cp -ravTf C:/run %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - for %%i in (*.zip) do echo %%~ni> zip_filename.txt
  - SET /P PKG_TARBALL=<zip_filename.txt
  - del zip_filename.txt
  - rename %PKG_TARBALL%.zip %PKG_TARBALL%_R%R_VER%.zip
  - echo Built tarball is %PKG_TARBALL%_R%R_VER%.zip

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
  - cat *.Rcheck\**\*.out
  - cat *.Rcheck\**\*.log    

after_test:
- 7z a testthat.zip *.Rcheck\**\*.Rout

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: testthat.zip
    name: Logs

  - path: '\*_*_*.zip'
    name: Bits

deploy:
  provider: GitHub
  description: 'Windows Binary'
  auth_token:
    secure: tc2Va9OWLH9H/uKPUKCUmv+q+wQpzRVJd6t8ckXjqzGnOo9eWyiQCmuuUjcuM3b8
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
